### ISSUE TITLE
Методы работают с целочисленным типом и принимают на вход два целочисленных параметра. Тут параметров не вижу

### ISSUE THREAD

**Issue by tallinn-learning** [VeronikaOstrovski/homework07#2]
https://github.com/VeronikaOstrovski/homework07/blob/0e68257a06c56b94d012ecbe2606c26a4758bb01/src/main/java/org/example/Calculator.java#L5

**Comment by VeronikaOstrovski** [comment]
Поправила. Проверьте, пожалуйста
