### ISSUE TITLE
тут нужно вызывать метод класса Калькулятор - а не просто ассерт который не относится ни к чему

### ISSUE THREAD

**Issue by tallinn-learning** [VeronikaOstrovski/homework07#3]
https://github.com/VeronikaOstrovski/homework07/blob/0e68257a06c56b94d012ecbe2606c26a4758bb01/src/test/java/org/example/CalculatorTest.java#L11

**Comment by VeronikaOstrovski** [comment]
Поправила. Проверьте, пожалуйста
